### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [p-e-w/language-javascript-semantic#22]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.1.0`) of this package:

1. Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `<pack-name>` package
1. Requiring `$` from `atom` is no longer supported. If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead: `{$} = require 'atom-space-pen-views'` or `$ = require 'jquery'` Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies. Or add `"jquery": "^2"` to your package dependencies.
1. The atom.syntax global is deprecated. Use atom.grammars instead.

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by p-e-w** [comment]
Fixed in v0.2.1. Please update.
