### ISSUE TITLE
Not applying semantic highlighting after switching the grammar

### ISSUE THREAD

**Issue by bfreis** [p-e-w/language-javascript-semantic#9]
Hi,

I've installed the package from Atom's Settings View, restarted Atom, and then switched the grammar of an open JavaScript file to "JavaScript (Semantic Highlighting)", just like the "Usage" section of the README says.

However, I don't see semantic highlighting applied to my code. Here's an example:
![image](https://cloud.githubusercontent.com/assets/261623/5639667/ef4cdef8-9601-11e4-82e2-021ba8ea2360.png)

I noticed that Atom seems to actually be truly using your highlighter -- changing from "JavaScript" to "JavaScript (Semantic Highlighting)" does modify colors a bit (ie, "true" goes from a shade of green to a shade of blue). But as you can see in the image, colors don't feel like they should, like I see in your screenshots :(

What did I do wrong?

Thanks,
Bruno

**Comment by Duder-onomy** [comment]
This is happening to me as well. It started when I upgraded to ATOM version `0.169.0`

**Comment by bfreis** [comment]
It was happening to me before 0.169.0. I believe I was using 0.166.0.

**Comment by rpavlov** [comment]
Same here :( I really miss this highlighting.

**Comment by cperryk** [comment]
Also seeing this. 0.172.0

**Comment by bfreis** [comment]
Now on 0.174.0 the package triggers some deprecation notices:

Deprecated calls
language-javascript-semantic (2 deprecations)
The atom.syntax global is deprecated. Use atom.grammars instead.
Called 1 timeCreate Issue on language-javascript-semantic repo
Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:316:11
Object.activate - /Users/bfreis/.atom/packages/language-javascript-semantic/lib/main.coffee:13:9
The atom.syntax global is deprecated. Use atom.grammars instead.
Called 1 timeCreate Issue on language-javascript-semantic repo
Atom.Object.defineProperty.get - /Applications/Atom.app/Contents/Resources/app/src/atom.js:316:11
Object.activate - /Users/bfreis/.atom/packages/language-javascript-semantic/lib/main.coffee:13:62

**Comment by Duder-onomy** [comment]
FOUND IT! This will temporarily fix your problem. 

Go to settings and turn off the Shadow Dom.
http://blog.atom.io/2015/01/05/enable-shadow-dom.html

Looks like this is enabled by default, the semantic highlighting scss file will need to be updated to pierce the shadow dom.

**Comment by bfreis** [comment]
Awesome! Thanks for the tip! Now it's working.

Looks like it won't be possible to disable Shadow DOM anymore on 1.0.0, though.

**Comment by p-e-w** [comment]
What changes are necessary for this to work with Shadow DOM?

**Comment by Duder-onomy** [comment]
@p-e-w I love this highlighting, my screen is the coolest in the office. 

This [article](http://blog.atom.io/2015/01/05/enable-shadow-dom.html) on upgrading.  Is the only thing I have found with any ideas on how to fix.

Looks like the selectors you use to give the elements colors need to be updated to use the `::shadow`  selector which will pierce the shadow dom boundary. I believe this is only selectors that descend from the `editor`. 

Looking at the source code of this repo. I am unsure how to accomplish this.  Though, my spider sense tells me that [this line](https://github.com/p-e-w/language-javascript-semantic/blob/master/stylesheets/semantic-colors.less#L22) needs to be updated.

If you don't have the time and can point me in the right direction. I will put in some work.

**Comment by p-e-w** [comment]
Thanks, so it might be as simple as prefixing that line with `::shadow`?

**Comment by DrDanRyan** [comment]
Hope this get fixed soon. I love the package but turning off shadow DOM breaks linter package which I have come to depend on heavily.

**Comment by mik01aj** [comment]
+1. Could anyone open a pull request for that?
